kind: pipeline
name: frontend

steps:
- name: build
  image: node
  commands:
  - cd frontend
  - npm ci
  - make build
- name: sync
  image: plugins/s3-sync:1
  settings:
    bucket: sthub.in.fkn.space
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    region: eu-central-1
    source: frontend/public
    target: /
    cloudfront_distribution: E2OHW6JPREC4E4

---
kind: pipeline
name: sthub

steps:
- name: build
  image: golang
  environment:
    GOOS: windows
    GOARCH: amd64
    PATH: $PATH:/go/bin
  commands:
  - go get -u github.com/GeertJohan/go.rice/rice
  - rice embed-go
  - go build
