service: sthub

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3::::sthub.in.fkn.space/*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  update-testships:
    handler: bin/update-testships
    events:
      - http:
          path: update-testships
          method: post
